kind: Service
apiVersion: v1
metadata:
  name: phenotips
  namespace: {{ NAMESPACE }}
  labels:
    name: phenotips
    deployment: {{ DEPLOY_TO }}
spec:
  ports:
  - port: {{ PHENOTIPS_SERVICE_PORT }}
  selector:
    name: phenotips
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: phenotips
  namespace: {{ NAMESPACE }}
  labels:
    name: phenotips
    deployment: {{ DEPLOY_TO }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: phenotips
        deployment: {{ DEPLOY_TO }}
    spec:
      priorityClassName: medium-priority
      containers:
      - name: phenotips-pod
        ports:
        - containerPort: {{ PHENOTIPS_SERVICE_PORT }}
          protocol: TCP
        imagePullPolicy: {{ IMAGE_PULL_POLICY }}
        image: {{ DOCKER_IMAGE_PREFIX }}/phenotips{{ DOCKER_IMAGE_TAG }}
        resources:
          requests:
            memory: "0.5Gi"
            cpu: "0.01"
          limits:
            memory: "3Gi"
            cpu: "2"
        env:
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: postgres.username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: postgres.password
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - /readiness_probe
      restartPolicy: Always
      dnsPolicy: ClusterFirst
