kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  namespace: {{ NAMESPACE }}
  labels:
    name: elasticsearch
    deployment: {{ DEPLOY_TO }}
spec:
  ports:
  - name: elasticsearch
    port: {{ ELASTICSEARCH_SERVICE_PORT }}
  selector:
    name: elasticsearch
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: elasticsearch
  namespace: {{ NAMESPACE }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: elasticsearch
        deployment: {{ DEPLOY_TO }}
    spec:
      volumes:
      - name: elasticsearch-dbpath
        gcePersistentDisk:
          # This disk must already exist.
          pdName: {{ CLUSTER_NAME }}-elasticsearch-disk
          fsType: ext4
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: {{ IMAGE_PULL_POLICY }}
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch-pod
        ports:
        - containerPort: {{ ELASTICSEARCH_SERVICE_PORT }}
          protocol: TCP
        imagePullPolicy: {{ IMAGE_PULL_POLICY }}
        image: {{ DOCKER_IMAGE_PREFIX }}/elasticsearch{{ DOCKER_IMAGE_TAG }}
        volumeMounts:
        - name: elasticsearch-dbpath
          mountPath: /elasticsearch-data
        env:
        - name: ELASTICSEARCH_SERVICE_PORT
          value: "{{ ELASTICSEARCH_SERVICE_PORT }}"
      restartPolicy: Always
      dnsPolicy: ClusterFirst
