apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: {{ NAMESPACE }}
  labels:
    name: elasticsearch
    deployment: {{ DEPLOY_TO }}
spec:
  version: {{ ELASTICSEARCH_VERSION }}
  image: {{ DOCKER_IMAGE_PREFIX }}/elasticsearch{{ DOCKER_IMAGE_TAG }}
  auth:
    roles:
      - secretName: elasticsearch-secrets
    fileRealm:
      - secretName: elasticsearch-secrets
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
  - name: master
    count: {{ ES_MASTER_NUM_PODS }}
    config:
      node.master: true
      node.data: false
      node.ingest: false
      node.ml: false
      node.remote_cluster_client: false
    podTemplate:
      metadata:
        labels:
          name: elasticsearch
          deployment: {{ DEPLOY_TO }}
      spec:
        initContainers:
          - name: sysctl
            securityContext:
              privileged: true
            command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        containers:
        - name: elasticsearch
          imagePullPolicy: {{ IMAGE_PULL_POLICY }}
  - name: client
    count: {{ ES_CLIENT_NUM_PODS }}
    config:
      node.master: false
      node.data: false
      node.ingest: false
      node.ml: false
      node.remote_cluster_client: false
    podTemplate:
      metadata:
        labels:
          name: elasticsearch
          deployment: {{ DEPLOY_TO }}
      spec:
        initContainers:
          - name: sysctl
            securityContext:
              privileged: true
            command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        containers:
        - name: elasticsearch
          imagePullPolicy: {{ IMAGE_PULL_POLICY }}
  - name: data
    count:  {{ ES_DATA_NUM_PODS }}
    config:
      node.master: false
      node.data: true
      node.ingest: false
      node.ml: false
      node.remote_cluster_client: false
    podTemplate:
      metadata:
        labels:
          name: elasticsearch
          deployment: {{ DEPLOY_TO }}
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        containers:
        - name: elasticsearch
          imagePullPolicy: {{ IMAGE_PULL_POLICY }}
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms{{ ELASTICSEARCH_JVM_MEMORY }} -Xmx{{ ELASTICSEARCH_JVM_MEMORY }}"
          resources:
            requests:
              memory: {{ ELASTCISEATCH_CONTAINER_MEMORY }}
            limits:
              memory: {{ ELASTCISEATCH_CONTAINER_MEMORY }}
# for use in mounting multiple disks to copy data - should not be used for real in production
#          volumeMounts:
#          - name: storage
#            mountPath: /data
#        volumes:
#        - name: storage
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: ssd-storage-class
        resources:
          requests:
            storage: {{ ES_DATA_DISK_SIZE }}
# for use in mounting multiple disks to copy data - should not be used for real in production
#    - metadata:
#        name: storage
#      spec:
#        accessModes: [ "ReadWriteOnce" ]
#        storageClassName: ssd-storage-class
#        resources:
#          requests:
#            storage: {{ ES_DATA_DISK_SIZE }}
