apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-data
  labels:
    component: elasticsearch
    role: data
spec:
  type: NodePort
  ports:
  - port: 9300
    nodePort: 30000
    name: transport
  selector:
    component: elasticsearch
    role: data
