language: node_js

python:
- '2.7'
node_js:
- '11.8.0'

install:
- ./install_dependencies.sh

script:
- python -Wonce -u manage.py test -p '*_tests.py' -v 3 reference_data seqr xbrowse --pythonpath ./deploy/docker/seqr/config
- cd ui/
- npm test

services:
- postgresql

notifications:
  slack:
    secure: tYNwi4kff+8FWbv+nWqKZt28Qez0Dv77rJG6nvdiaO7QgPZmaiG5l8NqYdxV63CMgNzHwTFAz8ca9uOoh06o7+HuiFNNiqXEAu8umLvlnvkKT6itSDyImxxD7ypitUwcBEKkNy1fxhrLRPQVLjxz37885kA/VtWpm19A5vQ8A7w=

