language: node_js

python:
- '2.7'
node_js:
- '7.2.1'

install:
- ./install_dependencies.sh

script:
- PYTHONPATH=.:./deploy/docker/seqr/config python -Wonce -u manage.py test -p '*_tests.py' -v 2 reference_data seqr xbrowse
- cd ui/
- npm test
- cd ..
- cd hail-elasticsearch-pipelines
- python -m unittest discover -p "*tests.py"
- cd ..

notifications:
  slack:
    secure: tYNwi4kff+8FWbv+nWqKZt28Qez0Dv77rJG6nvdiaO7QgPZmaiG5l8NqYdxV63CMgNzHwTFAz8ca9uOoh06o7+HuiFNNiqXEAu8umLvlnvkKT6itSDyImxxD7ypitUwcBEKkNy1fxhrLRPQVLjxz37885kA/VtWpm19A5vQ8A7w=

