language: python

python:
- '3.7'

node_js:
- '11.8.0'

services:
- docker

install:
- ./install_dependencies.sh

script:
- ./test_local_deployment.sh

addons:
  postgresql: '9.6'

notifications:
  slack:
    secure: tYNwi4kff+8FWbv+nWqKZt28Qez0Dv77rJG6nvdiaO7QgPZmaiG5l8NqYdxV63CMgNzHwTFAz8ca9uOoh06o7+HuiFNNiqXEAu8umLvlnvkKT6itSDyImxxD7ypitUwcBEKkNy1fxhrLRPQVLjxz37885kA/VtWpm19A5vQ8A7w=

