DEPLOY_TO: 'gcloud'
GCLOUD_PROJECT: 'seqr-project'
GCLOUD_ZONE: 'us-east1-d'
CLUSTER_NAME: 'seqr-cluster'
CLUSTER_NUM_NODES: 1
CLUSTER_MACHINE_TYPE: 'n1-highmem-2'   # n1-standard-2, n1-standard-4 .. n1-standard-64,  n1-highmem-2, n1-highcpu-2 ..

USE_EXTERNAL_POSTGRES_DB: false
POSTGRES_IP: 35.185.45.141
POSTGRES_USERNAME: postgres
POSTGRES_PASSWORD: ''   # v1IpFjrsP7k3iPg1
