apiVersion: v1
kind: Service
metadata:
  name: {{ PREFIX }}-postgres-svc
spec:
  ports:
  - port: 5432

---
kind: Endpoints
apiVersion: v1
metadata:
  name: {{ PREFIX }}-postgres-svc
subsets:
- addresses:
  - ip: {{ POSTGRES_IP }}
  ports:
  - port: 5432
