kind: Service
apiVersion: v1
metadata:
  name: postgres-svc
spec:
  ports:
  - port: {{ POSTGRES_PORT }}

---
kind: Endpoints
apiVersion: extensions/v1beta1
metadata:
  name: postgres-svc
subsets:
- addresses:
  - ip: {{ POSTGRES_IP }}
  ports:
  - port: {{ POSTGRES_PORT }}
