kind: Service
apiVersion: v1
metadata:
  name: postgres
spec:
  ports:
  - port: {{ POSTGRES_SERVICE_PORT }}

---
kind: Endpoints
apiVersion: extensions/v1beta1
metadata:
  name: postgres
subsets:
- addresses:
  - ip: {{ POSTGRES_IP }}
  ports:
  - port: {{ POSTGRES_SERVICE_PORT }}
