kind: Service
apiVersion: v1
metadata:
  name: elasticsearch-svc
spec:
  type: NodePort
  ports:
  - name: elasticsearch
    port: 30002
    nodePort: 30002
  selector:
    name: elasticsearch
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: elasticsearch
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: elasticsearch
    spec:
      volumes:
      - name: elasticsearch-data
        gcePersistentDisk:
          # This disk must already exist.
          pdName: {{ DEPLOY_TO }}-elasticsearch-disk
          fsType: ext4
      containers:
      - name: elasticsearch-pod
        image: {{ DOCKER_IMAGE_PREFIX }}/elasticsearch
        ports:
        - containerPort: 30001
          protocol: TCP
        imagePullPolicy: Always
        volumeMounts:
        - name: elasticsearch-data
          mountPath: /elasticsearch-data
      restartPolicy: Always
      dnsPolicy: ClusterFirst
