kind: Service
apiVersion: v1
metadata:
  name: pipeline-runner-svc
  labels:
    deployment: {{ DEPLOY_TO }}
spec:
  ports:
  - port: 35000
  selector:
    name: seqr
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: pipeline-runner
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: pipeline-runner
        deployment: {{ DEPLOY_TO }}
    spec:
      containers:
      - name: pipeline-runner-pod
        image: {{ DOCKER_IMAGE_PREFIX }}/pipeline-runner:{{ TIMESTAMP }}
        ports:
        - containerPort: 35000
          protocol: TCP
        imagePullPolicy: Always
        env:
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: postgres.username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: postgres.password
      restartPolicy: Always
      dnsPolicy: ClusterFirst
