---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: seqr
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: seqr
    spec:
      volumes:
      - name: seqr-code
        hostPath:
          path: {{ SEQR_CODE_PATH }}
      containers:
      - name: seqr-pod
        image: {{ DOCKER_IMAGE_PREFIX }}/seqr
        ports:
        - containerPort: 8000
          protocol: TCP
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: seqr-code
          mountPath: /seqr
        env:
        - name: POSTGRES_HOST
          value: postgres-svc
        - name: MONGO_HOST
          value: mongo-svc
        - name: PHENOTIPS_HOST
          value: phenotips-svc
        - name: MME_HOST
          value: matchbox-svc
      restartPolicy: Always
      dnsPolicy: ClusterFirst
