kind: Service
apiVersion: v1
metadata:
  name: seqr-svc
  labels:
    name: seqr
    deployment: {{ DEPLOY_TO }}
spec:
  ports:
  - port: {{ SEQR_PORT }}
  selector:
    name: seqr
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: seqr
  labels:
    name: seqr
    deployment: {{ DEPLOY_TO }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: seqr
        deployment: {{ DEPLOY_TO }}
    spec:
      containers:
      - name: seqr-pod
        image: {{ DOCKER_IMAGE_PREFIX }}/seqr:{{ TIMESTAMP }}
        ports:
        - containerPort: {{ SEQR_PORT }}
          protocol: TCP
        imagePullPolicy: Always
        env:
        - name: GCLOUD_PROJECT
          value: {{ GCLOUD_PROJECT }}
        - name: GCLOUD_ZONE
          value: {{ GCLOUD_ZONE }}
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: postgres.username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: postgres.password
        - name: OMIM_KEY
          valueFrom:
            secretKeyRef:
              name: seqr-secrets
              key: omim_key
        - name: POSTMARK_SERVER_TOKEN
          valueFrom:
            secretKeyRef:
              name: seqr-secrets
              key: postmark_server_token
        - name: POSTGRES_HOST
          value: postgres-svc
        - name: MONGO_HOST
          value: mongo-svc
        - name: PHENOTIPS_HOST
          value: phenotips-svc
        - name: MME_HOST
          value: matchbox-svc
      restartPolicy: Always
      dnsPolicy: ClusterFirst
