kind: Service
apiVersion: v1
metadata:
  name: solr-svc
spec:
  type: NodePort
  ports:
  - name: solr
    port: 30002
    nodePort: 30002
  - name: zk
    port: 31002
    nodePort: 31002
  selector:
    name: solr
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: solr
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: solr
    spec:
      volumes:
      - name: solr-data
        gcePersistentDisk:
          # This disk must already exist.
          pdName: {{ DEPLOY_TO }}-solr-disk
          fsType: ext4
      containers:
      - name: solr-pod
        image: {{ DOCKER_IMAGE_PREFIX }}/solr:{{ TIMESTAMP }}
        ports:
        - containerPort: 30002
          protocol: TCP
        - containerPort: 31002
          protocol: TCP
        imagePullPolicy: Always
        volumeMounts:
        - name: solr-data
          mountPath: /solr-data
      restartPolicy: Always
      dnsPolicy: ClusterFirst
