# Service config copied from https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/cloud/deploy.yaml
# and modified to add loadBalancerIP: {{CLUSTER_EXTERNAL_IP}}

# Source: ingress-nginx/templates/controller-service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    helm.sh/chart: ingress-nginx-2.10.0
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/version: 0.33.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: {{ CLUSTER_EXTERNAL_IP }}   # static IP pre-allocated.
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/component: controller
---
# docs on config options: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/
#kind: Ingress
#apiVersion: extensions/v1beta1
#metadata:
#  name: ingress-nginx
#  namespace: {{ NAMESPACE }}
#  annotations:
#    nginx.ingress.kubernetes.io/proxy-body-size: 8m
#spec:
#  tls:
#    - hosts:
#      - {{ CLUSTER_HOSTNAME }}
#      secretName: nginx-secrets
#  rules:
#    - host: {{ CLUSTER_HOSTNAME }}
#      http:
#        paths:
#        - path: /
#          backend:
#            serviceName: seqr
#            servicePort: {{ SEQR_SERVICE_PORT }}
