# Service config copied from https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/cloud/deploy.yaml
# and modified to add loadBalancerIP: {{CLUSTER_EXTERNAL_IP}}

# Source: ingress-nginx/templates/controller-service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    helm.sh/chart: ingress-nginx-3.10.1
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/version: 0.41.2
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: {{ CLUSTER_EXTERNAL_IP }}   # static IP pre-allocated.
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/component: controller
---
# ConfigMap modified to enable modsecurity, owasp crs
# Source: ingress-nginx/templates/controller-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    helm.sh/chart: ingress-nginx-3.10.1
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/version: 0.41.2
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
  name: ingress-nginx-controller
  namespace: ingress-nginx
data:
  enable-modsecurity: "true"
  modsecurity-snippet: |
    SecAuditLogType Serial
    SecAuditLog /dev/stdout
    SecAuditLogFormat JSON
    # local requests
    SecRuleRemoveById 920350
    # regex match for windows command injection, contained many false positives
    SecRuleRemoveById 932115
    Include /etc/nginx/owasp-modsecurity-crs/nginx-modsecurity.conf
    # adds 'application/vnd.ga4gh.matchmaker.v1.0+json' to the list of allowed content-types
    SecAction \
      "id:900220,\
      phase:1,\
      nolog,\
      pass,\
      t:none,\
      setvar:'tx.allowed_request_content_type=application/x-www-form-urlencoded|multipart/form-data|text/xml|application/xml|application/soap+xml|application/x-amf|application/json|application/octet-stream|text/plain|application/vnd.ga4gh.matchmaker.v1.0+json'"
---
# docs @ https://kubernetes.github.io/ingress-nginx/user-guide/basic-usage/
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: ingress-nginx
  namespace: {{ NAMESPACE }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine DetectionOnly
spec:
  tls:
    - hosts:
      - {{ CLUSTER_HOSTNAME }}
      secretName: nginx-secrets
  rules:
    - host: {{ CLUSTER_HOSTNAME }}
      http:
        paths:
        - path: /
          backend:
            serviceName: seqr
            servicePort: {{ SEQR_SERVICE_PORT }}
