kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  #host: {{ HOSTNAME }}
  tls:
    - secretName: nginx-secrets
  backend:
    serviceName: seqr
    servicePort: {{ SEQR_SERVICE_PORT }}
