kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: nginx
  namespace: {{ DEPLOY_TO }}
  labels:
    name: nginx
    deployment: {{ DEPLOY_TO }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
      - {{ CLUSTER_HOSTNAME }}
      secretName: nginx-secrets
  rules:
    - host: {{ CLUSTER_HOSTNAME }}
      http:
        paths:
        - backend:
            serviceName: seqr
            servicePort: {{ SEQR_SERVICE_PORT }}
          path: /
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-service
  namespace: {{ DEPLOY_TO }}
  labels:
    name: nginx
    deployment: {{ DEPLOY_TO }}
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  loadBalancerIP: {{ CLUSTER_EXTERNAL_IP }}  # static IP pre-allocated.
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: nginx
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  namespace: {{ DEPLOY_TO }}
  labels:
    name: nginx
    deployment: {{ DEPLOY_TO }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx/nginx-ingress:1.3.0
        imagePullPolicy: Always
        name: nginx
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        args:
          - -nginx-configmaps={{ DEPLOY_TO }}/nginx-config
          - -default-server-tls-secret={{ DEPLOY_TO }}/nginx-secrets
         #- -v=3 # Enables extensive logging. Useful for troubleshooting.
         #- -report-ingress-status
         #- -external-service=nginx
         #- -enable-leader-election
