version: '2.4'

services:
  postgres:
    image: gcr.io/seqr-project/postgres:gcloud-dev
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

  init-postgres:
    image: gcr.io/seqr-project/postgres:gcloud-dev
    depends_on:
      postgres:
        condition: service_healthy
    command: bash -c "
      psql -h postgres -U postgres -c 'CREATE DATABASE seqrdb';
      psql -h postgres -U postgres -c 'CREATE DATABASE reference_data_db';
      psql -h postgres -U postgres -c 'CREATE DATABASE xwiki';
      psql -h postgres -U postgres -c \"CREATE ROLE xwiki WITH CREATEDB LOGIN PASSWORD 'xwiki'\";
      psql -h postgres -U postgres -c 'GRANT ALL PRIVILEGES ON DATABASE xwiki TO xwiki';
      wget -N https://storage.googleapis.com/seqr-reference-data/gene_reference_data_backup.gz;
      psql -h postgres -U postgres reference_data_db <  <(gunzip -c gene_reference_data_backup.gz);"

  redis:
    image: gcr.io/seqr-project/redis:gcloud-dev
    ports:
      - 6379:6379

  elasticsearch:
    image: gcr.io/seqr-project/elasticsearch:gcloud-dev
    ports:
      - 9200:9200
    volumes:
      - ./data/elasticsearch:/elasticsearch-data

    healthcheck:
      test: ["CMD-SHELL", "curl localhost:9200"]
      interval: 10s
      timeout: 10s
      retries: 3

  kibana:
    image: gcr.io/seqr-project/kibana:gcloud-dev
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_SERVICE_HOSTNAME=elasticsearch
      - ELASTICSEARCH_SERVICE_PORT=9200
    depends_on:
      elasticsearch:
        condition: service_healthy

  phenotips:
    image: gcr.io/seqr-project/phenotips:gcloud-dev
    ports:
      - 8080:8080
    depends_on:
      - init-postgres

  seqr:
    image: gcr.io/seqr-project/seqr:gcloud-dev
    ports:
      - 8000:8000
    environment:
      - SEQR_GIT_BRANCH=dev
      - PYTHONPATH=/seqr
      - STATIC_MEDIA_DIR=/seqr_static_files
      - POSTGRES_SERVICE_HOSTNAME=postgres
      - ELASTICSEARCH_SERVICE_HOSTNAME=elasticsearch
      - PHENOTIPS_SERVICE_HOSTNAME=phenotips
      - REDIS_SERVICE_HOSTNAME=redis
      - PGHOST=postgres
      - PGUSER=postgres
      - GUNICORN_WORKER_THREADS=4

    depends_on:
      - init-postgres
      - elasticsearch
      - redis
      - phenotips
