---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ PREFIX }}mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: {{ PREFIX }}mongo
    spec:
      containers:
      - name: {{ PREFIX }}mongo-pod
        image: {{ DOCKER_IMAGE_PREFIX }}/mongo
        ports:
        - containerPort: 27017
          protocol: TCP
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
      dnsPolicy: ClusterFirst
