kind: Service
apiVersion: v1
metadata:
  name: pipeline-runner
  labels:
    name: pipeline-runner
    namespace: {{ NAMESPACE }}
    deployment: {{ DEPLOY_TO }}
spec:
  ports:
  - port: {{ PIPELINE_RUNNER_SERVICE_PORT }}
  selector:
    name: pipeline-runner
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: pipeline-runner
  namespace: {{ NAMESPACE }}
  labels:
    name: pipeline-runner
    deployment: {{ DEPLOY_TO }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: pipeline-runner
        deployment: {{ DEPLOY_TO }}
    spec:
      volumes:
      - name: data-dir
        hostPath:
          path: {{ MINIKUBE_DATA_DIR }}
      - name: gcloud-client-secrets-volume
        secret:
          secretName: gcloud-client-secrets
      containers:
      - name: pipeline-runner-pod
        image: {{ DOCKER_IMAGE_PREFIX }}/pipeline-runner:{{ TIMESTAMP }}
        ports:
        - containerPort: {{ PIPELINE_RUNNER_SERVICE_PORT }}
          protocol: TCP
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: data-dir
          mountPath: /data
        - name: gcloud-client-secrets-volume
          mountPath: /.config
          readOnly: true
        envFrom:
          - configMapRef:
              name: all-settings
        env:
        - name: POSTMARK_SERVER_TOKEN
          valueFrom:
            secretKeyRef:
              name: seqr-secrets
              key: postmark_server_token
        - name: GCLOUD_PROJECT      #  TODO can delete these and just rely on 'envFrom configMapRef' above once https://github.com/kubernetes/minikube/issues/2295 is fixed
          value: "{{ GCLOUD_PROJECT }}"
        - name: GCLOUD_ZONE
          value: "{{ GCLOUD_ZONE }}"
        - name: HOST_MACHINE_IP
          value: "{{ HOST_MACHINE_IP }}"
        - name: MATCHBOX_SERVICE_HOSTNAME
          value: "{{ MATCHBOX_SERVICE_HOSTNAME }}"
        - name: POSTGRES_SERVICE_HOSTNAME
          value: "{{ POSTGRES_SERVICE_HOSTNAME }}"
        - name: MONGO_SERVICE_HOSTNAME
          value: "{{ MONGO_SERVICE_HOSTNAME }}"
        - name: PHENOTIPS_SERVICE_HOSTNAME
          value: "{{ PHENOTIPS_SERVICE_HOSTNAME }}"
        - name: ELASTICSEARCH_SERVICE_HOSTNAME
          value: "{{ ELASTICSEARCH_SERVICE_HOSTNAME }}"
        - name: REDIS_SERVICE_HOSTNAME
          value: "{{ REDIS_SERVICE_HOSTNAME }}"
        - name: SEQR_SERVICE_PORT
          value: "{{ SEQR_SERVICE_PORT }}"
        - name: PHENOTIPS_SERVICE_PORT
          value: "{{ PHENOTIPS_SERVICE_PORT }}"
        - name: POSTGRES_SERVICE_PORT
          value: "{{ POSTGRES_SERVICE_PORT }}"
        - name: MATCHBOX_SERVICE_PORT
          value: "{{ MATCHBOX_SERVICE_PORT }}"
        - name: ELASTICSEARCH_SERVICE_PORT
          value: "{{ ELASTICSEARCH_SERVICE_PORT }}"
        - name: MONGO_SERVICE_PORT
          value: "{{ MONGO_SERVICE_PORT }}"
        - name: DEPLOY_TO
          value: "{{ DEPLOY_TO }}"
        - name: DEPLOY_TO_PREFIX
          value: "{{ DEPLOY_TO_PREFIX }}"
        - name: DEPLOYMENT_TYPE
          value: "{{ DEPLOYMENT_TYPE }}"
        - name: CLUSTER_NAME
          value: "{{ CLUSTER_NAME }}"
        - name: SEQR_GIT_BRANCH
          value: "{{ SEQR_GIT_BRANCH }}"
      restartPolicy: Always
      dnsPolicy: ClusterFirst
