# Service that connects to an elasticsearch instance running outside this kubernetes cluster
kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  namespace: {{ NAMESPACE }}
spec:
  ports:
    - port: {{ ELASTICSEARCH_SERVICE_EXTERNAL_PORT }}
---
kind: Endpoints
apiVersion: v1
metadata:
  name: elasticsearch
  namespace: {{ NAMESPACE }}
subsets:
  - addresses:
      - ip: {{ ELASTICSEARCH_SERVICE_EXTERNAL_IP }}
    ports:
      - port:  {{ ELASTICSEARCH_SERVICE_EXTERNAL_PORT }}
