# Service that connects to a mongo instance that's running directly on the host machine (in the case of minikube)
# or generally somewhere else outside this kubernetes cluster
kind: Service
apiVersion: v1
metadata:
  name: mongo
  namespace: {{ NAMESPACE }}
spec:
  ports:
    - port: {{ MONGO_SERVICE_EXTERNAL_PORT }}
---
kind: Endpoints
apiVersion: v1
metadata:
  name: mongo
  namespace: {{ NAMESPACE }}
subsets:
  - addresses:
      - ip: {{ MONGO_SERVICE_EXTERNAL_IP }}
    ports:
      - port:  {{ MONGO_SERVICE_EXTERNAL_PORT }}
