apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  postgres_username: 'cG9zdGdyZXM='        # output of `echo -n "postgres" | base64`
  postgres_password: 'ZGV2X3Bhc3N3b3Jk'    # output of `echo -n "dev_password" | base64`

#POSTGRES_PASSWORD: 'test'   # v1IpFjrsP7k3iPg1
