---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ PREFIX }}-phenotips
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: {{ PREFIX }}-phenotips
    spec:
      containers:
      - name: {{ PREFIX }}-phenotips-pod
        image: {{ DOCKER_IMAGE_PREFIX }}/phenotips
        ports:
        - containerPort: 8080
          protocol: TCP
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
      dnsPolicy: ClusterFirst
