kind: Service
apiVersion: v1
metadata:
  name: phenotips-svc
spec:
  ports:
  - port: {{ PHENOTIPS_PORT }}
  selector:
    name: phenotips
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: phenotips
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: phenotips
    spec:
      containers:
      - name: phenotips-pod
        image: {{ DOCKER_IMAGE_PREFIX }}/phenotips:{{ TIMESTAMP }}
        ports:
        - containerPort: {{ PHENOTIPS_PORT }}
          protocol: TCP
        imagePullPolicy: Always
        env:
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: postgres.username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: postgres.password
      restartPolicy: Always
      dnsPolicy: ClusterFirst
