kind: Service
apiVersion: v1
metadata:
  name: postgres-svc
spec:
  ports:
  - port: {{ POSTGRES_PORT }}
  selector:
    name: postgres
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: postgres
    spec:
      volumes:
      - name: postgres-dbpath
        hostPath:
          path: {{ POSTGRES_DBPATH }}
      containers:
      - name: postgres-pod
        image: {{ DOCKER_IMAGE_PREFIX }}/postgres:{{ TIMESTAMP }}
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: postgres.username
          #value: {{ POSTGRES_USERNAME }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: postgres.password
          #value: {{ POSTGRES_PASSWORD }}
        ports:
        - containerPort: {{ POSTGRES_PORT }}
          protocol: TCP
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: postgres-dbpath
          mountPath: /var/lib/postgresql/data
      restartPolicy: Always
      dnsPolicy: ClusterFirst
