kind: Service
apiVersion: v1
metadata:
  name: postgres-svc
  labels:
    name: postgres
    deployment: {{ DEPLOY_TO }}
spec:
  ports:
  - port: {{ POSTGRES_PORT }}
  selector:
    name: postgres
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: postgres
        deployment: {{ DEPLOY_TO }}
    spec:
      volumes:
      - name: postgres-dbpath
        gcePersistentDisk:
          # This disk must already exist.
          pdName: {{ DEPLOY_TO }}-postgres-disk
          fsType: ext4
      containers:
      - name: postgres-pod
        image: {{ DOCKER_IMAGE_PREFIX }}/postgres:{{ TIMESTAMP }}
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: postgres.username
          #value: {{ POSTGRES_USERNAME }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: postgres.password
          #value: {{ POSTGRES_PASSWORD }}
        ports:
        - containerPort: {{ POSTGRES_PORT }}
          protocol: TCP
        imagePullPolicy: Always
        volumeMounts:
        - name: postgres-dbpath
          mountPath: /var/lib/postgresql
      restartPolicy: Always
      dnsPolicy: ClusterFirst
