---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: postgres
    spec:
      volumes:
      - name: postgres-dbpath
        hostPath:
          path: {{ POSTGRES_DBPATH }}
      containers:
      - name: postgres-pod
        image: {{ DOCKER_IMAGE_PREFIX }}/postgres
        ports:
        - containerPort: 5432
          protocol: TCP
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: postgres-dbpath
          mountPath: /var/lib/postgresql/data
      restartPolicy: Always
      dnsPolicy: ClusterFirst
