DEPLOY_TO: 'gcloud-dev'
DEPLOY_TO_PREFIX: 'gcloud'
DEPLOYMENT_TYPE: 'dev'

GCLOUD_PROJECT: 'seqr-project'
GCLOUD_ZONE: 'us-central1-b'

DOCKER_IMAGE_PREFIX: 'gcr.io/seqr-project'

# gcloud settings
CLUSTER_NAME: 'seqr-cluster-dev'
CLUSTER_MACHINE_TYPE: 'n1-highmem-4'   # n1-standard-2, n1-standard-4 .. n1-standard-64,  n1-highmem-2, n1-highcpu-2 ..
CLUSTER_NUM_NODES: 1

CLUSTER_EXTERNAL_IP: '104.198.135.79'
CLUSTER_HOSTNAME: 'seqr-dev.broadinstitute.org'

MONGO_SERVICE_EXTERNAL_IP: 10.128.0.3  # broad-seqr
MONGO_SERVICE_EXTERNAL_PORT: 27017

ELASTICSEARCH_SERVICE_EXTERNAL_IP: 10.56.1.5
ELASTICSEARCH_SERVICE_EXTERNAL_PORT: 9200

SEQR_GIT_BRANCH: 'dev'
