DEPLOY_TO: 'gcloud-dev'
DEPLOY_TO_PREFIX: 'gcloud'
DEPLOYMENT_TYPE: 'dev'

GCLOUD_PROJECT: 'seqr-project'
GCLOUD_ZONE: 'us-central1-b'

DOCKER_IMAGE_PREFIX: 'gcr.io/seqr-project'

# gcloud settings
CLUSTER_NAME: 'ssd-seqr-cluster-dev'
CLUSTER_MACHINE_TYPE: 'n1-highmem-2'   # n1-standard-2, n1-standard-4 .. n1-standard-64,  n1-highmem-2, n1-highcpu-2 ..
CLUSTER_NUM_NODES: 2

CLUSTER_EXTERNAL_IP: '104.198.135.79'
CLUSTER_HOSTNAME: 'seqr-dev.broadinstitute.org'

USE_EXTERNAL_POSTGRES_DB: false
#EXTERNAL_POSTGRES_IP: '35.185.45.141'
#SERVICE_ACCOUNT_KEY_FILE: 'account-key-file-30ea80400948.json'

CLOUD_PROVIDER: 'google'
USE_GCLOUD_DATAPROC: yes

# ------------------------------------
#    elastic search cluster
# ------------------------------------
ES_CLUSTER_NAME: 'ssd-seqr-cluster-dev'
ES_CLUSTER_MACHINE_TYPE: 'n1-highmem-4'   # n1-standard-2, n1-standard-4 .. n1-standard-64,  n1-highmem-2, n1-highcpu-2 ..
ES_CLUSTER_NUM_NODES: 4

ES_DATA_NUM_PODS: 4
ES_CLIENT_NUM_PODS: 2
ES_MASTER_NUM_PODS: 3

ELASTICSEARCH_DISK_SIZE: 380
ELASTICSEARCH_JVM_MEMORY: 13g