#####################################################
####### SETTINGS THAT MAY NEED TO BE MODIFIED #######

CLUSTER_NAME: 'seqr-cluster-prod'
DEFAULT_POOL_MACHINE_TYPE: 'n1-highmem-8'
DEFAULT_POOL_NUM_NODES: 2

CLUSTER_EXTERNAL_IP: '35.194.17.244'
CLUSTER_HOSTNAME: 'seqr.broadinstitute.org'

ES_DATA_SERVICE_IP: 10.128.0.52

ENABLE_DATABASE_BACKUPS: true
DATABASE_BACKUP_BUCKET: seqr-backups

GUNICORN_WORKER_THREADS: 20    # number of webserver threads

SEQR_POD_MEMORY_LIMIT: 35Gi
REDIS_POD_MEMORY_LIMIT: 10Gi

# TODO remove in https://github.com/broadinstitute/seqr-private/issues/931
UPLOADED_PEDIGREE_FILE_RECIPIENTS: 'shall@broadinstitute.org,kdelano@broadinstitute.org'


###########################################################
####### SETTINGS THAT SHOULDN'T NEED TO BE MODIFIED #######

NAMESPACE: default

DEPLOY_TO: 'gcloud-prod'
DEPLOYMENT_TYPE: 'prod'
