#####################################################
####### SETTINGS THAT MAY NEED TO BE MODIFIED #######

CLUSTER_NAME: 'gcloud-dev-es'
CLUSTER_MACHINE_TYPE: 'n1-highmem-4'   # n1-standard-2, n1-standard-4 .. n1-standard-64,  n1-highmem-2, n1-highcpu-2 ..
# Need s one node per data pod
CLUSTER_NUM_NODES: 4
CLUSTER_NODE_LABELS: nodeType=data

KUBERNETES_VERSION: '1.16.13-gke.1'

ES_DATA_NUM_PODS: 3
ES_CLIENT_NUM_PODS: 2
ES_MASTER_NUM_PODS: 3

ES_DATA_DISK_SIZE: 3200
ELASTICSEARCH_JVM_MEMORY: 11g
ELASTICSEARCH_CONTAINER_MEMORY: 22Gi # should be 2x ELASTICSEARCH_JVM_MEMORY https://www.elastic.co/guide/en/elasticsearch/reference/7.8/heap-size.html

GCLOUD_PROJECT: 'seqr-project'
GCLOUD_ZONE: 'us-central1-b'

DISKS: es-data
ES_DATA_NUM_DISKS: 3
ES_DATA_DISK_TYPE: pd-ssd

#ES_DATA_SNAPSHOTS:  snapshot-es-data-1,  snapshot-es-data-2,  snapshot-es-data-3

###########################################################
####### SETTINGS THAT SHOULDN'T NEED TO BE MODIFIED #######

NAMESPACE: gcloud-dev-es

ES_CLUSTER_NAME: gcloud-dev-es
ELASTICSEARCH_VERSION: 7.8.1

DEPLOY_TO: 'gcloud-dev-es'
DEPLOY_TO_PREFIX: 'gcloud'
DEPLOYMENT_TYPE: 'dev'

CLUSTER_EXTERNAL_IP: ''
CLUSTER_HOSTNAME: ''
