#####################################################
####### SETTINGS THAT MAY NEED TO BE MODIFIED #######

CLUSTER_NAME: 'seqr-cluster-dev'
CLUSTER_MACHINE_TYPE: 'n1-highmem-4'   # n1-standard-2, n1-standard-4 .. n1-standard-64,  n1-highmem-2, n1-highcpu-2 ..
CLUSTER_NUM_NODES: 1

KUBERNETES_VERSION: '1.11.2-gke.18'

CLUSTER_EXTERNAL_IP: '104.198.135.79'
CLUSTER_HOSTNAME: 'seqr-dev.broadinstitute.org'
BASE_URL: 'https://seqr-dev.broadinstitute.org/'

ELASTICSEARCH_SERVICE_EXTERNAL_IP: 10.16.0.3
ELASTICSEARCH_SERVICE_EXTERNAL_PORT: 9200

SEQR_SERVICE_NODE_PORT: 30003

GCLOUD_PROJECT: 'seqr-project'
GCLOUD_ZONE: 'us-central1-b'

SEQR_GIT_BRANCH: 'dev'

SEQR_POD_MEMORY_LIMIT: 15Gi
REDIS_POD_MEMORY_LIMIT: 8Gi
PHENOTIPS_POD_MEMORY_LIMIT: 3Gi

UPLOADED_PEDIGREE_FILE_RECIPIENTS: ''

###########################################################
####### SETTINGS THAT SHOULDN'T NEED TO BE MODIFIED #######

NAMESPACE: gcloud-dev

DEPLOY_TO: 'gcloud-dev'
DEPLOY_TO_PREFIX: 'gcloud'
DEPLOYMENT_TYPE: 'dev'
