#####################################################
####### SETTINGS THAT MAY NEED TO BE MODIFIED #######

ELASTICSEARCH_SERVICE_EXTERNAL_IP: {{ HOST_MACHINE_IP }}  # default assumes elasticsearch is running on the same machine as minikube
ELASTICSEARCH_SERVICE_EXTERNAL_PORT: 9200

SEQR_SERVICE_NODE_PORT: 30003   # after deployment, seqr will be accessible at http://$(minikube ip):$SEQR_SERVICE_NODE_PORT . Node port range starts at 30000

MINIKUBE_DISK_SIZE: 100g        # how much disk space minikube can consume
# MINIKUBE_MEMORY: 12000, MINIKUBE_NUM_CPUS: 8  <-- these can optionally be set here to over-ride defaults

SEQR_GIT_BRANCH: 'master'       # the seqr pod will run this seqr code branch

# (optional) GCLOUD_PROJECT and GCLOUD_ZONE values are used to preconfigure gcloud command-line tools within pods to point to this project.
GCLOUD_PROJECT: 'seqr-project'
GCLOUD_ZONE: 'us-central1-b'


###########################################################
####### SETTINGS THAT SHOULDN'T NEED TO BE MODIFIED #######

NAMESPACE: minikube

DEPLOY_TO: 'minikube'
DEPLOY_TO_PREFIX: 'minikube'
DEPLOYMENT_TYPE: 'dev'

# paths inside the minikube VM
MINIKUBE_DATA_DIR: '/data'
POSTGRES_DBPATH:  '/data/postgres'
MONGO_DBPATH:  '/data/mongo'
ELASTICSEARCH_DBPATH:  '/data/elasticsearch'

CLUSTER_NAME: 'minikube'
CLUSTER_EXTERNAL_IP: '0.0.0.0'

MONGO_SERVICE_EXTERNAL_IP: {{ HOST_MACHINE_IP }}  # works if mongo is running on the same machine as minikube and the external-mongo-connector is deployed on your minikube cluster
MONGO_SERVICE_EXTERNAL_PORT: 27017
