DEPLOY_TO: 'minikube'
DEPLOY_TO_PREFIX: 'local'
DEPLOYMENT_TYPE: 'dev'

DOCKER_IMAGE_PREFIX: 'local/seqr'

USE_EXTERNAL_POSTGRES_DB: false

CLUSTER_NAME: 'minikube'
CLOUD_PROVIDER: 'local'

POSTGRES_DBPATH:  '/data/postgres'
MONGO_DBPATH:  '/data/mongo'
ELASTICSEARCH_DBPATH:  '/data/elasticsearch'

ELASTICSEARCH_JVM_MEMORY: 8g

GCLOUD_CLIENT_SECRETS: ~/.config/client_secrets.json
