# isolates secrets and other objects between different environments (minikube, gcloud-dev, gcloud-prod, etc)
# see: https://kubernetes.io/blog/2015/08/using-kubernetes-namespaces-to-manage/
apiVersion: v1
kind: Namespace
metadata:
  name: {{ NAMESPACE }}
---
apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass
metadata:
  name: high-priority
value: 1000000
globalDefault: false
---
apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass
metadata:
  name: medium-priority
value: 10000
globalDefault: false
