kind: Service
apiVersion: v1
metadata:
  name: redis
  namespace: {{ NAMESPACE }}
  labels:
    name: redis
    deployment: {{ DEPLOY_TO }}
spec:
  ports:
  - port: {{ REDIS_SERVICE_PORT }}
  selector:
    name: redis
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: redis
  namespace: {{ NAMESPACE }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: redis
        deployment: {{ DEPLOY_TO }}
    spec:
      containers:
      - name: redis-pod
        ports:
        - containerPort: {{ REDIS_SERVICE_PORT }}
          protocol: TCP
        imagePullPolicy: {{ IMAGE_PULL_POLICY }}
        image: {{ DOCKER_IMAGE_PREFIX }}/redis{{ DOCKER_IMAGE_TAG }}
        resources:
          requests:
            memory: "0.25Gi"
            cpu: "0.01"
          limits:
            memory: "2Gi"
            cpu: "0.5"
      restartPolicy: Always
      dnsPolicy: ClusterFirst
