apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: {{ NAMESPACE }}
  labels:
    name: kibana
    deployment: {{ DEPLOY_TO }}
spec:
  version: {{ ELASTICSEARCH_VERSION }}
  image: {{ DOCKER_IMAGE_PREFIX }}/kibana:{{ DOCKER_IMAGE_TAG }}
  count: 1
  elasticsearchRef:
    name: elasticsearch
  podTemplate:
    metadata:
      labels:
        name: kibana
        deployment: {{ DEPLOY_TO }}
  http:
    tls:
      selfSignedCertificate:
        disabled: true
