apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: {{ NAMESPACE }}
  labels:
    name: kibana
    deployment: {{ DEPLOY_TO }}
spec:
  version: {{ ELASTICSEARCH_VERSION }}
  image: {{ DOCKER_IMAGE_PREFIX }}/kibana{{ DOCKER_IMAGE_TAG }}
  count: 1
  config:
    elasticsearch.hosts:
      - http://{{ ELASTICSEARCH_SERVICE_HOSTNAME }}:{{ ELASTICSEARCH_SERVICE_PORT }}
    elasticsearch.username: kibana
    xpack.security.sameSiteCookies: None
    xpack.security.secureCookies: true
    server.customResponseHeaders: {"x-frame-options":"sameorigin"}
  secureSettings:
    - secretName: kibana-secrets
  podTemplate:
    metadata:
      annotations:
            linkerd.io/inject: enabled
      labels:
        name: kibana
        deployment: {{ DEPLOY_TO }}
  http:
    tls:
      selfSignedCertificate:
        disabled: true
