kind: Service
apiVersion: v1
metadata:
  name: kibana
  namespace: {{ NAMESPACE }}
  labels:
    name: kibana
    deployment: {{ DEPLOY_TO }}
spec:
  ports:
  - name: kibana
    port: {{ KIBANA_SERVICE_PORT }}
  selector:
    name: kibana
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: kibana
  namespace: {{ NAMESPACE }}
  labels:
    name: kibana
    deployment: {{ DEPLOY_TO }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: kibana
        deployment: {{ DEPLOY_TO }}
    spec:
      containers:
      - name: kibana-pod
        ports:
        - containerPort: {{ KIBANA_SERVICE_PORT }}
          protocol: TCP
        imagePullPolicy: {{ IMAGE_PULL_POLICY }}
        image: {{ DOCKER_IMAGE_PREFIX }}/kibana{{ DOCKER_IMAGE_TAG }}
        resources:
          requests:
            memory: "0.25Gi"
            cpu: "0.01"
          limits:
            memory: "1Gi"
            cpu: "0.5"
        env:
        - name: KIBANA_SERVICE_PORT
          value: "{{ KIBANA_SERVICE_PORT }}"
        - name: ELASTICSEARCH_SERVICE_HOSTNAME
          value: "{{ ELASTICSEARCH_SERVICE_HOSTNAME }}"
        - name: ELASTICSEARCH_SERVICE_PORT
          value: "{{ ELASTICSEARCH_SERVICE_PORT }}"
      restartPolicy: Always
      dnsPolicy: ClusterFirst
